//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_ua {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ua() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language.ua", typeof(Language_ua).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А.
        /// </summary>
        public static string A_acrchitect {
            get {
                return ResourceManager.GetString("A_acrchitect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вже зареєстровані?.
        /// </summary>
        public static string AlreadySignedUp {
            get {
                return ResourceManager.GetString("AlreadySignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Багто якогось тексту про те як авторизуватись за допомогою чогось.
        /// </summary>
        public static string AnotherLoginServiceText {
            get {
                return ResourceManager.GetString("AnotherLoginServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти з допомогою інших сервісів.
        /// </summary>
        public static string AnotherLoginServiceTitle {
            get {
                return ResourceManager.GetString("AnotherLoginServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архітектор.
        /// </summary>
        public static string Architect {
            get {
                return ResourceManager.GetString("Architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площа / об&apos;єм.
        /// </summary>
        public static string AreaVolume {
            get {
                return ResourceManager.GetString("AreaVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Б.
        /// </summary>
        public static string B_builder {
            get {
                return ResourceManager.GetString("B_builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПБ.
        /// </summary>
        public static string BR_builders_representative {
            get {
                return ResourceManager.GetString("BR_builders_representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будівельник.
        /// </summary>
        public static string Builder {
            get {
                return ResourceManager.GetString("Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представник будівельника.
        /// </summary>
        public static string BuildersRepresentative {
            get {
                return ResourceManager.GetString("BuildersRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект будівлі.
        /// </summary>
        public static string BuildingProject {
            get {
                return ResourceManager.GetString("BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість будівництва.
        /// </summary>
        public static string ConstructionCost {
            get {
                return ResourceManager.GetString("ConstructionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата додання.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перший раз тут?.
        /// </summary>
        public static string FirstTimeHere {
            get {
                return ResourceManager.GetString("FirstTimeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі проекти та додаткова докладна інформація на www.bindexis.ch.
        /// </summary>
        public static string FullInfoOnSite {
            get {
                return ResourceManager.GetString("FullInfoOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорочення.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to План додатку запланований на.
        /// </summary>
        public static string PlanningApplication {
            get {
                return ResourceManager.GetString("PlanningApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запамятати.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватись.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репорти.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підписання / Умови заплановані на.
        /// </summary>
        public static string SubscribeTermsPlanned {
            get {
                return ResourceManager.GetString("SubscribeTermsPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім`я.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Індекс.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
